---
title: "Preliminary Study"
author: "Yifei Liu"
date: 2023/11/25
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, message = FALSE}
library(tidyverse)
library(modelr)
library(purrr)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(rpart)
library(rpart.plot)
library(randomForest)
set.seed(1)
```


```{r}
#load mortality dataset
mort_data =
  read_csv("mortality_data_cleaned.csv") |> 
  janitor::clean_names() |>
  select(-group, everything())

convert_to_factor <- function(df, columns) {
  df[columns] <- lapply(df[columns], factor)
  return(df)
}

mort_tidy = 
  read_csv("mortality_data_cleaned.csv") |>
  janitor::clean_names()  |>
  convert_to_factor(c("group", "gender", "outcome", "hypertensive", 
                      "atrialfibrillation", "chd_with_no_mi", "diabetes", 
                      "deficiencyanemias", "depression", "hyperlipemia", 
                      "renal_failure", "copd"))
```




```{r}
#select patient outcome and complications
com_data =
  mort_data |>
  select(hypertensive:copd)

com_tidy =
  mort_tidy |>
  select(outcome, hypertensive:copd)

#select patient outcome and vital signs
sign_data =
  mort_data |>
  select(heart_rate:ef)

sign_tidy =
  mort_tidy |>
  select(outcome, heart_rate:ef)
```


```{r fig.width = 10, fig.height = 10}
#show correlation
corrplot(cor(com_data), type = "upper", diag = FALSE)
```

Interpretation:\
 - `outcome` seems strongly connected with `deficiencyanemias`, `renal_failure`.\ 
 - `hypertensive` shows strong correlation with `hyperlipemia` and `renal_failure`.\
 - `diabetes` shows strong correlation with `renal_failure`.\
 - `hyperlipemia` also shows strong correlation with `renal_failure`.\

```{r fig.width = 10, fig.height = 10}
#show correlation
corrplot(cor(sign_data), type = "upper", diag = FALSE)
```


```{r}
#decision tree
tree_model = rpart(outcome ~ ., data = sign_tidy, method = "class")
print(tree_model)
rpart.plot(tree_model)

#rf
rf_model = randomForest(outcome ~ ., data = sign_tidy)
importance(rf_model)
rfPermute::confusionMatrix(rf_model)
summary(rf_model)
varImpPlot(rf_model)


library(party)
tree_com = ctree(outcome ~ ., data = com_tidy)
plot(tree_com)

tree_sign = ctree(outcome ~ ., data = sign_tidy)
plot(tree_sign)

```


```{r}
#pca for vital signs
sign_names = 
  sign_data |>
  select(heart_rate:ef) |>
  colnames()

#pca using R build-in function prcomp()
vars_sign = sign_data[, sign_names]
pca_res_sign = prcomp(vars_sign, scale. = TRUE)
summary(pca_res_sign)

#pca using packages `FactoMineR`, `factoextra`
res_pca_sign = PCA(sign_data, scale.unit = TRUE, graph = TRUE)
#PCA() function would do the data standardization automatically.
#keep 5 dimensions as result.

get_eigenvalue(res_pca_sign)
#`variance.percent` explains the percentage of change. 70% would be adequate.

#scree plot
fviz_eig(res_pca_sign, addlabels = TRUE, ylim = c(0, 20))
#visualize the contributions of each dimension.

#result
var_sign <- get_pca_var(res_pca_sign) 
var_sign$coord
#shown by correlation

fviz_pca_var(res_pca_sign, col.var = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
#based on above results (`var_com$coord`)
#basically,
#(a) positive correlated variables are grouped together,
#(b) negative correlated variables are located on opposite sides of the origin,
#(c) the distance between the variable and the origin measures the quality of the variable. Variables that are far from the origin are well represented.

corrplot(var_sign$cos2, is.corr=FALSE)
#shows the quality of variables.

var_sign$contrib
#shown by contribution

fviz_contrib(res_pca_sign, choice = "var", axes = 1, top = 10)
fviz_contrib(res_pca_sign, choice = "var", axes = 1:5, top = 10)

#colored individuals
fviz_pca_ind(res_pca_sign,
             geom.ind = "point",
             col.ind = as.character(mort_tidy$outcome),
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE,
             legend.title = "Groups")
```


