---
title: "Mortality Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
```


```{r,include=FALSE}

# Define a function to convert multiple columns to factors
convert_to_factor <- function(df, columns) {
  df[columns] <- lapply(df[columns], factor)
  return(df)
}

# Load the data and preprocess it
mortality_data <- read_csv("mortality_data.csv") %>%
  janitor::clean_names() %>%
  drop_na(outcome) %>%
  convert_to_factor(., c("group", "gendera", "outcome", "hypertensive", 
                         "atrialfibrillation", "chd_with_no_mi", "diabetes", 
                         "deficiencyanemias", "depression", "hyperlipemia", 
                         "renal_failure", "copd")) %>%
  rename(gender = gendera)  # Rename gendera to gender after conversion


# Imputing numerical columns with mean value 
numerical_columns <- sapply(mortality_data, is.numeric)
mortality_data[numerical_columns] <- lapply(mortality_data[numerical_columns], function(x) {
   ifelse(is.na(x), mean(x, na.rm = TRUE), x)
})

write_csv(mortality_data, "mortality_data_cleaned.csv")

mortality_data_EDA <- mortality_data %>%
  mutate(
    group = recode(group, `1` = "Group 1", `2` = "Group 2"),
    gender = recode(gender, `1` = "Male", `2` = "Female"),
    outcome = recode(outcome, `0` = "Alive", `1` = "Death")
  ) %>%
  mutate_if(is.factor, as.character)

  
```


Lab Results Analysis
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------


```{r}
selectInput(
    inputId = "index",
    label = h3("Select Index"),
    choices = c("creatinine", "lactic_acid", "urea_nitrogen", "leucocyte", "glucose", "anion_gap", "pco2"),
    selected = "creatinine"
  )


```




Row{data-height=650}
-----------------------------------------------------------------------

### Lab Results Analysis

```{r}
renderPlotly({

variable <- input$index
    plot_ly(mortality_data_EDA %>% drop_na(.data[[variable]]), 
            x = ~.data[[variable]], color = ~as.factor(outcome),
            type = "scatter", mode = "lines", fill = "tozeroy") %>%
      layout(title = paste(variable, "Levels by Outcome"),
             xaxis = list(title = variable),
             yaxis = list(title = "Density"))
  
})

```

